# Generated by Django 4.2.6 on 2024-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=100)),
                ('image', models.EmailField(max_length=254, unique=True)),
                ('season', models.CharField(max_length=128)),
                ('category', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('stars', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
